name: default

on:
  push:
    branches: ["*"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: cargo build --verbose
      - name: Check Formatting
        run: cargo fmt --check
      - name: Run Tests
        run: cargo test --verbose

